name: Publish Extension

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Navigate to Theme Directory
      run: cd pico-8-theme

    - name: Install Dependencies
      run: npm install

    - name: Publish to Marketplace
      run: npx vsce publish -p ${{ secrets.VSCE_PAT }}


